spring:
  application:
    name: customer-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:custdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Customer Service Application
    version: 1.0.0
    description: DEMO JPA Spring Boot Application with Actuator

#    logging:
#      level:
#        root: ${LOG_LEVEL:DEBUG}

#baeldung:
#    presentation:
#        name: ${MSG:"Hello World"}
