spring:
  application:
    name: customer-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:custdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
          probability: 1.0


info:
  app:
    name: Customer Service Application
    version: 1.0.0
    description: DEMO JPA Spring Boot Application with Actuator

order:
      service:
        url: ${ORDER_SERVICE_URL}

welcome:
  msg: ${WELCOME_MSG:"Default is Hello World"}

tracing:
 url: ${JAEGER_URL:http://jaeger:4318/v1/traces}


logging:
  pattern:
    console: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
