#apiVersion: v1
#kind: Service
#metadata:
#  name: jaeger
#spec:
#  selector:
#    app: jaeger
#  ports:
#    - name: ui
#      port: 16686
#      targetPort: 16686
#    - name: collector
#      port: 14250
#      targetPort: 14250
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: jaeger
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: jaeger
#  template:
#    metadata:
#      labels:
#        app: jaeger
#    spec:
#      containers:
#        - name: jaeger
#          image: jaegertracing/all-in-one:latest
#          ports:
#            - containerPort: 16686
#            - containerPort: 14250
#            - containerPort: 4318
#          env:
#            - name: COLLECTOR_OTLP_ENABLED
#              value: "true"

apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: collector
      port: 14250
      targetPort: 14250
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686  # UI
            - containerPort: 4317   # OTLP gRPC
            - containerPort: 4318   # OTLP HTTP
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
